services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - evetcare-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P ${DB_PASSWORD:-YourStrong@Passw0rd} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - evetcare-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  db-init:
    build:
      context: .
      dockerfile: Dockerfile.db-init
    environment:
      - DB_SERVER=sqlserver
      - SA_PASSWORD=${DB_PASSWORD:-YourStrong@Passw0rd}
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - evetcare-network
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=eVetCare;User Id=sa;Password=${DB_PASSWORD:-YourStrong@Passw0rd};TrustServerCertificate=true;MultipleActiveResultSets=true
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER:-guest}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD:-guest}
      - Jwt__Key=${JWT_KEY:-YourSuperSecretKeyHereMakeItLongEnoughForSecurity}
      - Jwt__Issuer=${JWT_ISSUER:-eVetCare}
      - Jwt__Audience=${JWT_AUDIENCE:-eVetCare}
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
    depends_on:
      db-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - evetcare-network
    volumes:
      - ./eVetCare/wwwroot/images:/app/wwwroot/images
    restart: unless-stopped

  notifications:
    build:
      context: .
      dockerfile: Dockerfile.notifications
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=eVetCare;User Id=sa;Password=${DB_PASSWORD:-YourStrong@Passw0rd};TrustServerCertificate=true;MultipleActiveResultSets=true
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER:-guest}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD:-guest}
    depends_on:
      db-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - evetcare-network
    restart: unless-stopped

volumes:
  sqlserver_data:
  rabbitmq_data:

networks:
  evetcare-network:
    driver: bridge
